data:
  data_dir: 'data/'
  train_csv_file: 'train.csv'
  train_image_dir: 'train_images/'
  test_csv_file: 'test.csv'
  test_image_dir: 'test_images/'

model:
  batch_size: 128
  epochs: 1
  learning_rate: 0.0008
  weight_decay: 0.01

output:
  checkpoint_dir: 'outputs/checkpoint/'

